### ISSUE TITLE
Scripts do not support PKCS12 keystore imports

### ISSUE THREAD

**Issue by mprzybylski** [derrekyoung/AppD-SSL-Cert-Utils#1]
Hi Derrek,

We just had a customer who tried to import a PKCS12 keystore with these scripts which is currently unsupported.

The docs for doing so in the controller are here...  https://docs.appdynamics.com/display/PRO41/Controller+SSL+and+Certificates#ControllerSSLandCertificates-ImportanExistingKeypairintotheKeystore
...if you want to add support in your scripts.

Best regards,
Mike Przybylski

**Comment by derrekyoung** [comment]
Mike, thanks for this. 

I see a couple ways forward:
1. Exit out if trying to import p12. Give a nice message about how to find the docs.
2. Modify the script to support p12.

Would it be reasonable for my updated script to exclude the openssl step, assuming they've already done that?
`openssl pkcs12 -inkey private.key -in cert.crt -export -out keystore.p12`

**Comment by derrekyoung** [comment]
Mike,

I added logic to exit out if they try to use a P12 cert. The messages directs them to the official docs for Controller/EUM. That'll work for now, and hopefully avoid some customer confusion. I can add real support later.

-Derrek
